# config file for fisicus app
#############################

# fully qualified target sitemap url
# example: https://www.yourwebsite.com/sitemaps/sitemap.xml
sitemap: "https://b-nova.com/sitemaps/sitemap.xml"

# filter patterns which are going to be matched against the url locs contained in the target sitemap
# example: /blog/*, !/service/promotion.html
filter: "/home/content/*"

# port this web service is going to be served on. default port if none is being specified is 8080.
# example: 8000
port: "8080"